export const COMPANY_BOOKING_LIST_REQUEST = "COMPANY_BOOKING_LIST_REQUEST";
export const COMPANY_BOOKING_LIST_SUCCESS = "COMPANY_BOOKING_LIST_SUCCESS";
export const COMPANY_BOOKING_LIST_FAIL = "COMPANY_BOOKING_LIST_FAIL";

export const BOOKING_STORE_REQUEST = "BOOKING_STORE_REQUEST";
export const BOOKING_STORE_SUCCESS = "BOOKING_STORE_SUCCESS";
export const BOOKING_STORE_FAIL = "BOOKING_STORE_FAIL";

export const BOOKING_DETAIL_REQUEST = "BOOKING_DETAIL_REQUEST";
export const BOOKING_DETAIL_SUCCESS = "BOOKING_DETAIL_SUCCESS";
export const BOOKING_DETAIL_FAIL = "BOOKING_DETAIL_FAIL";

export const VENDOR_BOOKING_LIST_REQUEST = "VENDOR_BOOKING_LIST_REQUEST";
export const VENDOR_BOOKING_LIST_SUCCESS = "VENDOR_BOOKING_LIST_SUCCESS";
export const VENDOR_BOOKING_LIST_FAIL = "VENDOR_BOOKING_LIST_FAIL";

export const BOOKING_UPDATE_REQUEST = "BOOKING_UPDATE_REQUEST";
export const BOOKING_UPDATE_SUCCESS = "BOOKING_UPDATE_SUCCESS";
export const BOOKING_UPDATE_FAIL = "BOOKING_UPDATE_FAIL";