export const BOOKING_LIST_REQUEST = "BOOKING_LIST_REQUEST";
export const BOOKING_LIST_SUCCESS = "BOOKING_LIST_SUCCESS";
export const BOOKING_LIST_FAIL = "BOOKING_LIST_FAIL";

export const BOOKING_STORE_REQUEST = "BOOKING_STORE_REQUEST";
export const BOOKING_STORE_SUCCESS = "BOOKING_STORE_SUCCESS";
export const BOOKING_STORE_FAIL = "BOOKING_STORE_FAIL";