export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const SHOW_MODAL_REJECT = "SHOW_MODAL_REJECT";
export const HIDE_MODAL_REJECT = "HIDE_MODAL_REJECT";

export const SHOW_MODAL_APPROVE = "SHOW_MODAL_APPROVE";
export const HIDE_MODAL_APPROVE = "HIDE_MODAL_APPROVE";